package cli

import (
	"github.com/spf13/cobra"
)

var refCmd = &cobra.Command{
	Use:   "ref",
	Short: "Reference data lookups",
	Long:  "Commands for listing Tessitura reference data (lookup tables).",
}

func init() {
	refCmd.AddCommand(refAppealCategoriesCmd)
	refCmd.AddCommand(refActivityStatusesCmd)
	refCmd.AddCommand(refActivityTypesCmd)
	refCmd.AddCommand(refAddressTypesCmd)
	refCmd.AddCommand(refAffiliationTypesCmd)
	refCmd.AddCommand(refAliasTypesCmd)
	refCmd.AddCommand(refAssociationTypesCmd)
	refCmd.AddCommand(refBusinessUnitsCmd)
	refCmd.AddCommand(refCampaignCategoriesCmd)
	refCmd.AddCommand(refConstituencyTypesCmd)
	refCmd.AddCommand(refConstituentGroupsCmd)
	refCmd.AddCommand(refConstituentInactivesCmd)
	refCmd.AddCommand(refConstituentProtectionTypesCmd)
	refCmd.AddCommand(refConstituentTypeAffiliatesCmd)
	refCmd.AddCommand(refConstituentTypesCmd)
	refCmd.AddCommand(refContactLogActivityTypesCmd)
	refCmd.AddCommand(refContactPermissionCategoriesCmd)
	refCmd.AddCommand(refContactPermissionTypesCmd)
	refCmd.AddCommand(refContactPointCategoriesCmd)
	refCmd.AddCommand(refContactPointCategoryPurposesCmd)
	refCmd.AddCommand(refContactPointPurposeCategoriesCmd)
	refCmd.AddCommand(refContactPointPurposesCmd)
	refCmd.AddCommand(refContactTypesCmd)
	refCmd.AddCommand(refContributionDesignationsCmd)
	refCmd.AddCommand(refContributionImportSetsCmd)
	refCmd.AddCommand(refCountriesCmd)
	refCmd.AddCommand(refDeliveryMethodsCmd)
	refCmd.AddCommand(refDesignationCodesCmd)
	refCmd.AddCommand(refDonationLevelsCmd)
	refCmd.AddCommand(refElectronicAddressTypesCmd)
	refCmd.AddCommand(refGendersCmd)
	refCmd.AddCommand(refInactiveReasonsCmd)
	refCmd.AddCommand(refInterestCategoriesCmd)
	refCmd.AddCommand(refInterestTypesCmd)
	refCmd.AddCommand(refKeywordCategoriesCmd)
	refCmd.AddCommand(refKeywordConstituentTypesCmd)
	refCmd.AddCommand(refKeywordsCmd)
	refCmd.AddCommand(refLanguagesCmd)
	refCmd.AddCommand(refLoginTypesCmd)
	refCmd.AddCommand(refMachineSettingsCmd)
	refCmd.AddCommand(refMailIndicatorsCmd)
	refCmd.AddCommand(refMembershipBenefitFrequenciesCmd)
	refCmd.AddCommand(refMembershipBenefitTypesCmd)
	refCmd.AddCommand(refMembershipLevelCategoriesCmd)
	refCmd.AddCommand(refMembershipLevelTrendsCmd)
	refCmd.AddCommand(refMembershipPeriodsCmd)
	refCmd.AddCommand(refMembershipStandingsCmd)
	refCmd.AddCommand(refMembershipStatusesCmd)
	refCmd.AddCommand(refNameStatusesCmd)
	refCmd.AddCommand(refNoteTypesCmd)
	refCmd.AddCommand(refOrderCategoriesCmd)
	refCmd.AddCommand(refOriginalSourcesCmd)
	refCmd.AddCommand(refPaymentTypesCmd)
	refCmd.AddCommand(refPerformanceStatusesCmd)
	refCmd.AddCommand(refPhilanthropyTypesCmd)
	refCmd.AddCommand(refPlanPrioritiesCmd)
	refCmd.AddCommand(refPlanSourcesCmd)
	refCmd.AddCommand(refPlanStatusesCmd)
	refCmd.AddCommand(refPlanTypesCmd)
	refCmd.AddCommand(refPlannedGivingCodesCmd)
	refCmd.AddCommand(refPlannedGivingFundingsCmd)
	refCmd.AddCommand(refPlannedGivingGiftTypesCmd)
	refCmd.AddCommand(refPlannedGivingOnFilesCmd)
	refCmd.AddCommand(refPlannedGivingPurposesCmd)
	refCmd.AddCommand(refPlannedGivingSourcesCmd)
	refCmd.AddCommand(refPlannedGivingStatusesCmd)
	refCmd.AddCommand(refPerformanceTypesCmd)
	refCmd.AddCommand(refPhoneIndicatorsCmd)
	refCmd.AddCommand(refPhoneTypesCmd)
	refCmd.AddCommand(refPrefixesCmd)
	refCmd.AddCommand(refPriceCategoriesCmd)
	refCmd.AddCommand(refPriceTypeCategoriesCmd)
	refCmd.AddCommand(refPriceTypeGroupsCmd)
	refCmd.AddCommand(refPronounsCmd)
	refCmd.AddCommand(refRecognitionTypesCmd)
	refCmd.AddCommand(refRelationshipCategoriesCmd)
	refCmd.AddCommand(refReportCategoriesCmd)
	refCmd.AddCommand(refReportTypesCmd)
	refCmd.AddCommand(refSalesChannelsCmd)
	refCmd.AddCommand(refSeatCodesCmd)
	refCmd.AddCommand(refSeatStatusesCmd)
	refCmd.AddCommand(refSeasonsCmd)
	refCmd.AddCommand(refSectionsCmd)
	refCmd.AddCommand(refStatesCmd)
	refCmd.AddCommand(refSuffixesCmd)
	refCmd.AddCommand(refTheatersCmd)
	refCmd.AddCommand(refUserGroupsCmd)
}
